name: mh_assistant
description: "Mental health assistant"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2
  go_router: ^17.2.3
  freezed_annotation: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^8.1.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  fl_chart: ^0.70.2
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.0
  geolocator: ^13.0.2
  geolocator_web: ^4.1.3
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  latlong2: ^0.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.15.0
  riverpod_generator: ^4.0.3
  json_serializable: ^6.13.0
  freezed: ^3.2.5

  
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/data/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
